### PR TITLE
Update views.py (firxed a couple of typos)

### PR DESCRIPTION
**Pull request by vecna**
Title was duplicated in Description, I guess by mistake 

I'm still getting error of malformed (I checked, is because of the "d" in "date")
(also, I was trying to put a comment in the file via github, but seems can't be done anymore?)

we'll see some validator as next thing

@nikonikoniko

### CODE REVIEW

**Comment by nikonikoniko** [comment]
@vecna what sort of validator would you like?

I was planning on using django forms to clean the data before it goes to the ORM and into the database - which is standard practice.  

would you also like to do validation on the incoming data to make sure it fits the form?

x

**Comment by Hadi-Khatib** [comment]
@nikonikoniko @vecna It's online on the live website https://syrianarchive.org/database/2245/ :)

**Comment by nikonikoniko** [comment]
@Hadi-Khatib did you verify it?

I should probably not let them show up on the frontend unless they are verified

**Comment by Hadi-Khatib** [comment]
@nikonikoniko no I didn't verify it yet.

**Comment by nikonikoniko** [comment]
@Hadi-Khatib fixed.  only backend until validated

**Pull request merged**
